name: Bug Report
description: Report bugs or issues.
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report! The more info you provide, the more we can help you.

  - type: textarea
    attributes:
      label: Describe the bug
      description: Clear and concise description of what the bug. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: I am doing… What I expect is… What actually happening is…
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Link to Minimal Reproducible Example
      description: Please provide a link to a minimal repository that can reproduce the problem. This makes investigating issues and helping you out significantly easier! For most issues, you will likely get asked to provide a minimal reproducible example so why not add one now :) If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "needs reproduction" label. If no reproduction is provided after 3 days, it will be auto-closed.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps or code snippets to reproduce the behavior.
    validations:
      required: false

  - type: input
    attributes:
      label: Package Version
      description: What version of kysely-migrate are you using?
      placeholder: x.y.z
    validations:
      required: true

  - type: input
    attributes:
      label: TypeScript Version
      description: What version of TypeScript are you using? kysely-migrate requires `typescript@>=5`.
      placeholder: x.y.z
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      description: Anything that will give us more context about the issue you are encountering. (You can attach images or files by clicking this area to highlight and then dragging files in.)
    validations:
      required: false

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting this issue, please make sure you do the following.
      options:
        - label: Checked there isn't [already an issue](https://github.com/tmm/kysely-migrate/issues) that exists for the bug you encountered.
          required: true
        - label: Added a minimal reproduction.
          required: true
