name: Verify
on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Lint code
        run: pnpm format && pnpm lint:fix

      - name: Update package version
        run: pnpm version:update
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore: format'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: pnpm build

      - name: Publint
        run: pnpm test:build

      - name: Check for unused files, dependencies, and exports
        run: pnpm knip --production --ignore-internal

  types:
    name: Types
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check types
        run: pnpm typecheck

  test:
    name: Test
    env:
      database_host: localhost
      database_name: km
      database_password: foobarbaz
      database_username: dev
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.34
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: km
          MYSQL_PASSWORD: foobarbaz
          MYSQL_USER: dev
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306
      postgres:
        image: postgres
        env:
          POSTGRES_DB: km
          POSTGRES_PASSWORD: foobarbaz
          POSTGRES_USER: dev
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
        ports:  
          - 5432:5432
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Set up databases
        run: |
          mysql --host 127.0.0.1 --port 3306 -uroot -e 'SET GLOBAL log_bin_trust_function_creators = 1;'

      - name: Run tests
        run: pnpm test:cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4